### ISSUE TITLE
Run failed, Exception: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by zmcgrath96** [zrolfs/MetaMorpheus#106] opened 2020-04-29 16:51 UTC
I am using some mock hybrid peptide data and generating the corresponding mzML files for these spectra. I am using a small database of 4 proteins with only ~200 spectra in the mzML file. However, when I try and run NeoFusion, i get the error in the title. Please let me know if there is anything I can provide you with to help out. Thanks

**Comment by zrolfs** [comment] 2020-04-29 16:55
Thanks for reaching out!
Do you know which task it failed on? Were any parameters different than the default?
Would you be willing to share your database and mzml file so I can reproduce the crash? That would be the fastest way for me to get a fix out to you. You can e-mail me at zrolfs@wisc.edu.

**Comment by zrolfs** [comment] 2020-04-30 14:38
Thank you for sharing the files! I was able to reproduce the crash and it looks like an issue with your mzML file. There is a scan entry for spectrum #18, but no spectrum (xml object "binaryDataArrayList"). If I copy in a spectrum from another scan, I'm able to run it just fine. I'm going to close the issue for now, but let me know if you have any other issues/questions!

**Closed as completed by zrolfs** 2020-04-30 14:38 UTC
